### ISSUE TITLE
ValueError :868100000

### ISSUE THREAD

**Issue by frankdunn** [DvdGiessen/lopy-nano-gateway#1]
Hi 

I am using your exact code and the nanogateway is connecting to ttn . On startup I get a ValueError 868100000 .  If  I use frequency=903900000 I get no errors . I updated the firmware 2 days ago .

**Comment by DvdGiessen** [comment]
Hey @frankdunn,

That's unexpected, the code works fine here. What is the exact error you're getting, and at which point does it occur? A full console output with the logging + the stack trace might help figure out what is going on, perhaps I'd be able to help.

You can also try using the @pycom variant; they've merged my changes into their version so you're not missing out on anything while I expect their version to stay more up to date. :)

https://github.com/pycom/pycom-libraries/tree/master/examples/lorawan-nano-gateway

**Comment by frankdunn** [comment]
Hi

Thanks for the response, I believe the problem is caused because I have the
915MHz  firmware installed. I can confirm this tonight .If I still have
problems I can forward more information.

Regards
Frank Dunn
